# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:
# !pip install numpy
import numpy as np
# formula = weight / (height**2) * 730
# height = [69, 70, 71, 72, 73, 74, 75]
# weight = [110, 120, 130, 140, 150, 160, 170]

# have two lists : height and weight
# convert list into NDArrays [np.array]
# height = height**2
# bmi = weight / (height)* 730
# create a function that takes a height and weight to calc bmi
# Step 1
def calculate_bmi(weight, height):
# convert list into numpy arrays
    weight = np.array(weight)
    height = np.array(height)
# calculate bmi
    bmi =  weight / (height**2)* 730
    return f'The Body Mass Index on the lists are: \n{bmi}'

# if the list below then
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

bmi_value =  calculate_bmi(weight, height)
print(bmi_value)

The Body Mass Index on the lists are: 
[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [14]:

# takes in two parameters
# ---parameters(matrix needs rows and columns).. rows and columns[two parameters]
# creates a random matrix based off of those parameters 
# ---matrix can be (4x4)
# extra: additional parameters taking in to allow user to choose the shape and data type of the matrix
# ---- extra two will be shape, data_type?
# what additional parameters?
# ---shape defaults to none, datatype defaults to float
# returns random matrix of given shape and data_type
# note: astype(): method in numpy used to change
# the datatype of NDArray from one dtype to another
#  It creates a copy of the array, and converts the type of the copy to the specified data type

# SOLUTION
def create_random_matrix(row, column, data_type, shape=None):
#     setting matrix shape such that if not specified then default
    if shape is not None:
        matrix_shape = shape
    else:
        matrix_shape = (row, column)
#     creates random matrix with user specified shape and datatype
    return np.random.rand(row, column).astype(data_type)

# USER test
random_matrix = create_random_matrix(4,4,int) #'int' user desired datatype..

print(f'Random matrix created:\n {random_matrix}')

Random matrix created:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [16]:
import csv
import numpy as np
# running a differential operation [r = arr10 - arr5]
# data = redsox_hitting_2017.txt ...2018
# Pseudocode: 
#1. define a func that opens data [redsox 2017 and 2018]
# 2. load the data for both years
# 3. get SLG column from array.. for clear representation of data
# 4. calculate the average SLG for both years
# 5. compare average... return the year with the highest average...


In [30]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data
#Use this function to actually open the data inside of a NDArray

bos_data_2017 = load_data('../Data_analytics assignment/redsox_2017_hitting.txt')
bos_data_2017

print('\n')

bos_data_2018 = load_data('../Data_analytics assignment/redsox_2018_hitting.txt')
bos_data_2018

# using the index of the SLG column.. get data
slg_2017 = bos_data_2017['SLG']
print(f'The SLG column for 2017:\n{slg_2017}')

print('\n')
slg_2018 = bos_data_2018['SLG']
print(f'The SLG column for 2018:\n {slg_2018}')

print('\n')
# calculate the mean for both 2017 and 2018
mean_slg_2017 = np.mean(slg_2017)
print(f'The mean SLG value for redsox in 2017:\n {mean_slg_2017}')

mean_slg_2018 = np.mean(slg_2018)
print(f'The mean SLG value for redsox in 2018:\n {mean_slg_2018}')
print('\n')
# running a differential operation
# using <,> = in this;
if mean_slg_2017 > mean_slg_2018:
    print(f'With an average SLG of {mean_slg_2017}, 2017 was a better year for redsox')
elif mean_slg_2017 < mean_slg_2018:
    print(f'With an average SLG of {mean_slg_2018}, 2018 looks like a better year for redsox')
else:
    print('Both years were equal based on SLG')



The SLG column for 2017:
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]


The SLG column for 2018:
 [0.279 0.433 0.388 0.522 0.433 0.465 0.403 0.64  0.629 0.411 0.283 0.328
 0.395 0.507 0.311 0.415 0.389 0.261 0.091 0.167]


The mean SLG value for redsox in 2017:
 0.393347829580307
The mean SLG value for redsox in 2018:
 0.38749998807907104


With an average SLG of 0.393347829580307, 2017 was a better year for redsox
